orte = [
    ("Berlin", "Berlin"),
    ("Hamburg", "Hamburg"),
    ("München", "Bayern"),
    ("Köln", "Nordrhein-Westfalen"),
    ("Frankfurt am Main", "Hessen"),
    ("Stuttgart", "Baden-Württemberg"),
    ("Düsseldorf", "Nordrhein-Westfalen"),
    ("Dortmund", "Nordrhein-Westfalen"),
    ("Essen", "Nordrhein-Westfalen"),
    ("Leipzig", "Sachsen"),
    ("Bremen", "Bremen"),
    ("Dresden", "Sachsen"),
    ("Hannover", "Niedersachsen"),
    ("Nürnberg", "Bayern"),
    ("Duisburg", "Nordrhein-Westfalen"),
    ("Bochum", "Nordrhein-Westfalen"),
    ("Wuppertal", "Nordrhein-Westfalen"),
    ("Bielefeld", "Nordrhein-Westfalen"),
    ("Bonn", "Nordrhein-Westfalen"),
    ("Münster", "Nordrhein-Westfalen"),
    ("Karlsruhe", "Baden-Württemberg"),
    ("Mannheim", "Baden-Württemberg"),
    ("Augsburg", "Bayern"),
    ("Wiesbaden", "Hessen"),
    ("Gelsenkirchen", "Nordrhein-Westfalen"),
    ("Mönchengladbach", "Nordrhein-Westfalen"),
    ("Braunschweig", "Niedersachsen"),
    ("Kiel", "Schleswig-Holstein"),
    ("Chemnitz", "Sachsen"),
    ("Aachen", "Nordrhein-Westfalen"),
    ("Halle (Saale)", "Sachsen-Anhalt"),
    ("Magdeburg", "Sachsen-Anhalt"),
    ("Freiburg im Breisgau", "Baden-Württemberg"),
    ("Krefeld", "Nordrhein-Westfalen"),
    ("Lübeck", "Schleswig-Holstein"),
    ("Oberhausen", "Nordrhein-Westfalen"),
    ("Erfurt", "Thüringen"),
    ("Mainz", "Rheinland-Pfalz"),
    ("Rostock", "Mecklenburg-Vorpommern"),
    ("Kassel", "Hessen"),
    ("Hagen", "Nordrhein-Westfalen"),
    ("Saarbrücken", "Saarland"),
    ("Hamm", "Nordrhein-Westfalen"),
    ("Mülheim an der Ruhr", "Nordrhein-Westfalen"),
    ("Ludwigshafen am Rhein", "Rheinland-Pfalz"),
    ("Potsdam", "Brandenburg"),
    ("Leverkusen", "Nordrhein-Westfalen"),
    ("Oldenburg", "Niedersachsen"),
    ("Osnabrück", "Niedersachsen"),
    ("Solingen", "Nordrhein-Westfalen"),
    ("Heidelberg", "Baden-Württemberg"),
    ("Herne", "Nordrhein-Westfalen"),
    ("Neuss", "Nordrhein-Westfalen"),
    ("Darmstadt", "Hessen"),
    ("Paderborn", "Nordrhein-Westfalen"),
    ("Regensburg", "Bayern"),
    ("Ingolstadt", "Bayern"),
    ("Würzburg", "Bayern"),
    ("Fürth", "Bayern"),
    ("Wolfsburg", "Niedersachsen"),
    ("Offenbach am Main", "Hessen"),
    ("Ulm", "Baden-Württemberg"),
    ("Heilbronn", "Baden-Württemberg"),
    ("Pforzheim", "Baden-Württemberg"),
    ("Göttingen", "Niedersachsen"),
    ("Bottrop", "Nordrhein-Westfalen"),
    ("Recklinghausen", "Nordrhein-Westfalen"),
    ("Reutlingen", "Baden-Württemberg"),
    ("Bremerhaven", "Bremen"),
    ("Koblenz", "Rheinland-Pfalz"),
    ("Bergisch Gladbach", "Nordrhein-Westfalen"),
    ("Jena", "Thüringen"),
    ("Remscheid", "Nordrhein-Westfalen"),
    ("Erlangen", "Bayern"),
    ("Moers", "Nordrhein-Westfalen"),
    ("Siegen", "Nordrhein-Westfalen"),
    ("Hildesheim", "Niedersachsen"),
    ("Salzgitter", "Niedersachsen"),
    ("Kaiserslautern", "Rheinland-Pfalz"),
    ("Witten", "Nordrhein-Westfalen"),
    ("Gütersloh", "Nordrhein-Westfalen"),
    ("Iserlohn", "Nordrhein-Westfalen"),
    ("Gütersloh", "Nordrhein-Westfalen"),
    ("Gütersloh", "Nordrhein-Westfalen"),
    ("Gütersloh", "Nordrhein-Westfalen"),
    ("Gütersloh", "Nordrhein-Westfalen"),
    ("Gütersloh", "Nordrhein-Westfalen")
]

orte.sort(key=lambda x: x[0])

print(orte)