{
 "title": "WetterSchweiz",
 "time": { "from": "now-6h", "to": "now+30m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Kanton",
    "query": "select canton  from  weather_data where dt> now() - interval 2 hour and (country = \"CH\" or country=\"VA\") "
   },
   {
    "name": "Ort",
    "query": "select distinct city from  weather_data  where (dt> now() - interval 2 hour)  and canton=\"$Kanton\""
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  city as Ort, canton as Kanton, temperature as \"°C\", pressure as mBar, humidity as Feuchte,\n wind_direction as \"W.Richtung\", DATE_FORMAT(time_inserted,\"%H:%m:%s\") as Messung  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and (time_inserted - interval 1 hour) < now()\norder by dt desc\nlimit 3\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select \n    weather_main as Himmel,\n    CASE\n        WHEN wind_direction >= 337.5 OR wind_direction < 22.5 THEN 'Nord'\n        WHEN wind_direction >= 22.5 AND wind_direction < 67.5 THEN 'Nordost'\n        WHEN wind_direction >= 67.5 AND wind_direction < 112.5 THEN 'Ost'\n        WHEN wind_direction >= 112.5 AND wind_direction < 157.5 THEN 'Südost'\n        WHEN wind_direction >= 157.5 AND wind_direction < 202.5 THEN 'Süd'\n        WHEN wind_direction >= 202.5 AND wind_direction < 247.5 THEN 'Südwest'\n        WHEN wind_direction >= 247.5 AND wind_direction < 292.5 THEN 'West'\n        WHEN wind_direction >= 292.5 AND wind_direction < 337.5 THEN 'Nordwest'\n    END as Windrichtung from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 30 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  { "title": "Aktuelle Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperatur",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  temperature as \"°C\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 35 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  dewpoint(temperature,humidity) as \"Taupunkt\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and time_inserted > now() - INTERVAL 33 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Feuchte",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  humidity as \"%\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 30 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Druck",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  pressure as \"hPa\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 30 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Niederschlag",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  rain_down_1h as \"mm\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 30 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Sonne",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  100-clouds as \"%\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 30 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Wind Ø",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  wind_speed as \"km/h\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 30 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  { "title": "Verlauf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  temperature as Mittel, \n        temperature_min as Min,\n        temperature_max as Max,\n        dewpoint(temperature,humidity) as Taupunkt,\n        time_inserted as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Feuchte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  humidity as Feucht, \n        time_inserted as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  pressure as Druck, \n        time_inserted as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Wolken",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  clouds as Wolken, \n        time_inserted as Zeit from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Niederschlag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  rain_down_1h as Niederschlaf, \n        time_inserted as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Wind ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  wind_speed as Wind, \n        time_inserted as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Extremwerte Klicken sie auf die Spalte nach der Sie sortieren wollen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Extremwerte",
   "type": "table",
   "description": "sort by column clicking on the column by which you want to sort",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  city as Ort, temperature as Temp, wind_speed*3.6 as Wind, rain_down_1h as Niederschlag, \n        DATE_FORMAT(time_inserted, '%H:%i') as Zeit, time_inserted, now()\n        from weather_data \nwhere (time_inserted + interval 30 minute )  > now() and (country= \"CH\" or country =\"VA\")\nORDER BY temperature\n\n"
    }
   ]
  }
 ]
}